#!/bin/bash
# install.sh — macOS/Linux 一次性安装脚本。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
HOST_NAME="com.aicli.cheatsheet_updater"
MANIFEST_FILE="$HOST_NAME.json"
OS_NAME="$(uname -s)"

case "$OS_NAME" in
  Darwin)
    INSTALL_DIR="$HOME/Library/Application Support/aicli-cheatsheet"
    CHROME_DIRS=("$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts")
    EDGE_DIR="$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
    ;;
  Linux)
    INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/aicli-cheatsheet"
    CHROME_DIRS=(
      "${XDG_CONFIG_HOME:-$HOME/.config}/google-chrome/NativeMessagingHosts"
      "${XDG_CONFIG_HOME:-$HOME/.config}/chromium/NativeMessagingHosts"
    )
    EDGE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/microsoft-edge/NativeMessagingHosts"
    ;;
  *)
    echo "❌ 不支持的系统：$OS_NAME。Windows 请运行 install.ps1。"
    exit 1
    ;;
esac

echo "=== AI CLI 速查表 — 本地更新桥接 安装程序 ==="
echo ""

# ── 1. 检查依赖 ────────────────────────────────────────────────────────────────

PYTHON_BIN="$(command -v python3 || true)"
if [ -z "$PYTHON_BIN" ]; then
  echo "❌ 没找到 python3，请先安装 Python 3 再重新运行本脚本。"
  exit 1
fi
echo "✅ python3：$("$PYTHON_BIN" --version) ($PYTHON_BIN)"

CLAUDE_BIN=""
for p in \
  "$HOME/.local/bin/claude" \
  "$HOME/.npm-global/bin/claude" \
  "/usr/local/bin/claude" \
  "/opt/homebrew/bin/claude" \
  "$(command -v claude 2>/dev/null)"; do
  if [ -x "$p" ]; then
    CLAUDE_BIN="$p"
    break
  fi
done

if [ -z "$CLAUDE_BIN" ]; then
  echo "⚠️  没找到 claude 命令。"
  echo "   本功能需要 Claude Code CLI：npm install -g @anthropic-ai/claude-code"
  echo "   安装好 claude 后，重新运行本脚本即可，或者先继续完成安装。"
else
  echo "✅ claude：$CLAUDE_BIN"
fi

# ── 2. 部署文件到 ~/Library ────────────────────────────────────────────────────
# 放在 Library 而非插件目录，以避免 macOS 对 Downloads 等目录的访问限制。

echo ""
echo "正在部署到：$INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cp "$SCRIPT_DIR/host.py" "$INSTALL_DIR/host.py"
chmod 700 "$INSTALL_DIR" "$INSTALL_DIR/host.py"
echo "✅ host.py 已更新"

# 已有安装时，询问是否只更新 host.py、跳过重新配置
if [ -f "$INSTALL_DIR/run.sh" ]; then
  echo ""
  echo "检测到已有安装（$INSTALL_DIR/run.sh）。"
  read -rp "仅更新 host.py，保留现有配置？[Y/n]: " UPDATE_ONLY
  UPDATE_ONLY="${UPDATE_ONLY:-Y}"
  if [[ "$UPDATE_ONLY" =~ ^[Yy]$ ]]; then
    echo ""
    echo "=== 更新完成 ==="
    echo ""
    echo "请完全退出浏览器（Cmd+Q），重新打开后即可使用更新后的功能。"
    exit 0
  fi
  echo "继续重新配置…"
fi

# ── 3. 配置 claude 调用方式 ────────────────────────────────────────────────────

echo ""
echo "Claude Code 调用配置："
echo "  [1] 使用当前 shell 环境（默认，会继承你终端里的 ANTHROPIC_BASE_URL 等变量）"
echo "  [2] 强制走官方 Claude API（取消所有自定义 API 变量，走 ~/.claude/ 里的登录会话）"
echo "  [3] 自定义（手动填写 API Base URL 和 Auth Token）"
read -rp "请选择 [1/2/3]，直接回车默认选 1：" API_CHOICE
API_CHOICE="${API_CHOICE:-1}"

# 凭据与脚本分离：密钥写入独立的 credentials.env（chmod 600），run.sh 仅 source 它。
CREDS_FILE="$INSTALL_DIR/credentials.env"
EXTRA_ENV=""   # 仅存放非密钥内容（如 unset 语句），会内联进 run.sh
SOURCE_CREDS=""  # 若存在密钥文件，run.sh 加载它的语句

# 旧版可能把密钥内联在 run.sh 里，重新配置时先清掉残留的密钥文件
rm -f "$CREDS_FILE"

if [ "$API_CHOICE" = "2" ]; then
  EXTRA_ENV=$(cat << 'ENVEOF'
# 强制走官方 Claude API（取消所有自定义变量）
unset ANTHROPIC_BASE_URL
unset ANTHROPIC_API_KEY
unset ANTHROPIC_AUTH_TOKEN
unset ANTHROPIC_MODEL
unset ANTHROPIC_DEFAULT_HAIKU_MODEL
unset ANTHROPIC_DEFAULT_SONNET_MODEL
unset ANTHROPIC_DEFAULT_OPUS_MODEL
unset CLAUDE_CODE_SUBAGENT_MODEL
unset CLAUDE_CODE_EFFORT_LEVEL
unset ENABLE_TOOL_SEARCH
unset CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS
ENVEOF
)
elif [ "$API_CHOICE" = "3" ]; then
  read -rp "ANTHROPIC_BASE_URL（如 https://api.deepseek.com/anthropic）: " CUSTOM_URL
  read -rsp "ANTHROPIC_AUTH_TOKEN（你的 API Key，输入时不显示）: " CUSTOM_TOKEN
  echo ""
  read -rp "ANTHROPIC_MODEL（如 deepseek-chat，留空跳过）: " CUSTOM_MODEL
  printf -v QUOTED_URL '%q' "$CUSTOM_URL"
  printf -v QUOTED_TOKEN '%q' "$CUSTOM_TOKEN"

  # 先以 600 权限创建空文件再写入，避免密钥短暂以宽松权限落盘
  ( umask 177; : > "$CREDS_FILE" )
  {
    echo "# Auto-generated by install.sh — contains API secrets. Do not commit or share."
    echo "export ANTHROPIC_BASE_URL=$QUOTED_URL"
    echo "export ANTHROPIC_AUTH_TOKEN=$QUOTED_TOKEN"
    if [ -n "$CUSTOM_MODEL" ]; then
      printf -v QUOTED_MODEL '%q' "$CUSTOM_MODEL"
      echo "export ANTHROPIC_MODEL=$QUOTED_MODEL"
    fi
  } >> "$CREDS_FILE"
  chmod 600 "$CREDS_FILE"
  printf -v QUOTED_CREDS '%q' "$CREDS_FILE"
  SOURCE_CREDS="[ -f $QUOTED_CREDS ] && . $QUOTED_CREDS"
  echo "✅ 密钥已写入独立文件（权限 600）：$CREDS_FILE"
fi

# ── 4. 生成 run.sh ─────────────────────────────────────────────────────────────

RUN_SH="$INSTALL_DIR/run.sh"
printf -v QUOTED_PROJECT_DIR '%q' "$PROJECT_DIR"
printf -v QUOTED_INSTALL_HOST '%q' "$INSTALL_DIR/host.py"
printf -v QUOTED_PYTHON '%q' "$PYTHON_BIN"
cat > "$RUN_SH" << RUNEOF
#!/bin/bash
# Auto-generated by install.sh — do not edit manually, re-run install.sh to reconfigure.
# API 密钥（如有）存放在 credentials.env，由下方 source 语句加载，不内联在本文件中。
$EXTRA_ENV
$SOURCE_CREDS
export AICLI_PROJECT_DIR=$QUOTED_PROJECT_DIR
exec $QUOTED_PYTHON $QUOTED_INSTALL_HOST "\$@"
RUNEOF
chmod 700 "$RUN_SH"
echo "✅ run.sh 已生成：$RUN_SH"

# ── 5. 询问扩展 ID ─────────────────────────────────────────────────────────────

echo ""
echo "需要你的浏览器扩展 ID："
echo "  Chrome：打开 chrome://extensions/，开启开发者模式，找到「AI CLI 速查表」，"
echo "          卡片上会显示一串字母，如 abcdefghijklmnopabcdefghijklmnop"
echo "  Edge：  打开 edge://extensions/，步骤相同"
read -rp "请粘贴扩展 ID: " EXTENSION_ID

if [ -z "$EXTENSION_ID" ]; then
  echo "❌ 扩展 ID 不能为空。请先在浏览器里加载好插件，获取 ID 后重新运行本脚本。"
  exit 1
fi
if [[ ! "$EXTENSION_ID" =~ ^[a-z]{32}$ ]]; then
  echo "❌ 扩展 ID 格式不对（应为 32 位小写字母，如 abcdefghijklmnopabcdefghijklmnop）。"
  echo "   请在 chrome://extensions 开发者模式下确认正确的 ID 再重新运行。"
  exit 1
fi

# ── 6. 写入 Native Messaging manifest ─────────────────────────────────────────

write_manifest() {
  local TARGET_DIR="$1"
  mkdir -p "$TARGET_DIR"
  cat > "$TARGET_DIR/$MANIFEST_FILE" << MEOF
{
  "name": "$HOST_NAME",
  "description": "AI CLI 速查表插件的本地更新桥接程序",
  "path": "$RUN_SH",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXTENSION_ID/"
  ]
}
MEOF
  echo "✅ 已注册到：$TARGET_DIR/$MANIFEST_FILE"
}

for CHROME_DIR in "${CHROME_DIRS[@]}"; do
  write_manifest "$CHROME_DIR"
done

read -rp "同时注册到 Edge？[y/N]: " EDGE_CHOICE
if [[ "$EDGE_CHOICE" =~ ^[Yy]$ ]]; then
  EDGE_DIR="$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
  write_manifest "$EDGE_DIR"
fi

# ── 7. 完成 ───────────────────────────────────────────────────────────────────

echo ""
echo "=== 安装完成 ==="
echo ""
echo "请完全退出浏览器（Cmd+Q），重新打开后，插件里的「查询并写入」按钮即可使用。"
echo ""
echo "如需重新配置（更换 API 或更新扩展 ID），直接重新运行本脚本即可。"
