#!/bin/bash
# This file is auto-generated by install.sh and placed in:
#   ~/Library/Application Support/aicli-cheatsheet/run.sh
#
# Do not commit this file — it contains user-specific paths and API settings.
# Run native-host/install.sh to generate it for your environment.
#
# Example of what the generated file looks like:
#
#   export ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic"
#   export ANTHROPIC_AUTH_TOKEN="your-api-key-here"
#   export AICLI_PROJECT_DIR="/path/to/ai-cli-cheatsheet-extension"
#   exec /usr/bin/python3 "$HOME/Library/Application Support/aicli-cheatsheet/host.py" "$@"
