@echo off
rem This file is auto-generated by install.ps1 and placed in:
rem   %APPDATA%\aicli-cheatsheet\run.bat
rem
rem Do not commit this file — it contains user-specific paths and API settings.
rem Run native-host\install.ps1 to generate it for your environment.
rem
rem Example of what the generated file looks like:
rem
rem   set "ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic"
rem   set "ANTHROPIC_AUTH_TOKEN=your-api-key-here"
rem   set "AICLI_PROJECT_DIR=C:\path\to\ai-cli-cheatsheet-extension"
rem   "C:\Python312\python.exe" "%APPDATA%\aicli-cheatsheet\host.py" %*
